/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AppModuleRouteImport } from './routes/app.$module'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DevIntegrationStatusRouteImport } from './routes/dev.integration-status'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as AppPatientsIndexRouteImport } from './routes/app.patients.index'
import { Route as AppPatientsNewRouteImport } from './routes/app.patients.new'
import { Route as AppPatientsIdIndexRouteImport } from './routes/app.patients.$id.index'
import { Route as AppPatientsIdEditRouteImport } from './routes/app.patients.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIntegrationStatusRoute = DevIntegrationStatusRouteImport.update({
  id: '/dev/integration-status',
  path: '/dev/integration-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdIndexRoute = AppPatientsIdIndexRouteImport.update({
  id: '/patients/$id/',
  path: '/patients/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdEditRoute = AppPatientsIdEditRouteImport.update({
  id: '/patients/$id/edit',
  path: '/patients/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/appointments': typeof AppointmentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/tenders': typeof TendersRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$module': typeof AppModuleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/integration-status': typeof DevIntegrationStatusRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/blog/': typeof BlogIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/app/patients/$id/edit': typeof AppPatientsIdEditRoute
  '/app/patients/$id/': typeof AppPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/appointments': typeof AppointmentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/tenders': typeof TendersRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$module': typeof AppModuleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/integration-status': typeof DevIntegrationStatusRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/blog': typeof BlogIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients': typeof AppPatientsIndexRoute
  '/app/patients/$id/edit': typeof AppPatientsIdEditRoute
  '/app/patients/$id': typeof AppPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/appointments': typeof AppointmentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRoute
  '/tenders': typeof TendersRoute
  '/testimonials': typeof TestimonialsRoute
  '/app/$module': typeof AppModuleRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/integration-status': typeof DevIntegrationStatusRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/blog/': typeof BlogIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/app/patients/new': typeof AppPatientsNewRoute
  '/app/patients/': typeof AppPatientsIndexRoute
  '/app/patients/$id/edit': typeof AppPatientsIdEditRoute
  '/app/patients/$id/': typeof AppPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/appointments'
    | '/cart'
    | '/contact'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/tenders'
    | '/testimonials'
    | '/app/$module'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/reports'
    | '/app/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/blog/$slug'
    | '/dev/integration-status'
    | '/doctors/$id'
    | '/services/$id'
    | '/shop/$id'
    | '/blog/'
    | '/doctors/'
    | '/services/'
    | '/shop/'
    | '/app/patients/new'
    | '/app/patients/'
    | '/app/patients/$id/edit'
    | '/app/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/appointments'
    | '/cart'
    | '/contact'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/tenders'
    | '/testimonials'
    | '/app/$module'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/reports'
    | '/app/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/blog/$slug'
    | '/dev/integration-status'
    | '/doctors/$id'
    | '/services/$id'
    | '/shop/$id'
    | '/blog'
    | '/doctors'
    | '/services'
    | '/shop'
    | '/app/patients/new'
    | '/app/patients'
    | '/app/patients/$id/edit'
    | '/app/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/appointments'
    | '/cart'
    | '/contact'
    | '/departments'
    | '/events'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/tenders'
    | '/testimonials'
    | '/app/$module'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/reports'
    | '/app/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/blog/$slug'
    | '/dev/integration-status'
    | '/doctors/$id'
    | '/services/$id'
    | '/shop/$id'
    | '/blog/'
    | '/doctors/'
    | '/services/'
    | '/shop/'
    | '/app/patients/new'
    | '/app/patients/'
    | '/app/patients/$id/edit'
    | '/app/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AppointmentsRoute: typeof AppointmentsRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PortalRoute: typeof PortalRoute
  TendersRoute: typeof TendersRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevIntegrationStatusRoute: typeof DevIntegrationStatusRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  ShopIdRoute: typeof ShopIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/integration-status': {
      id: '/dev/integration-status'
      path: '/dev/integration-status'
      fullPath: '/dev/integration-status'
      preLoaderRoute: typeof DevIntegrationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients/': {
      id: '/app/patients/'
      path: '/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/new': {
      id: '/app/patients/new'
      path: '/patients/new'
      fullPath: '/app/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/$id/': {
      id: '/app/patients/$id/'
      path: '/patients/$id'
      fullPath: '/app/patients/$id/'
      preLoaderRoute: typeof AppPatientsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/$id/edit': {
      id: '/app/patients/$id/edit'
      path: '/patients/$id/edit'
      fullPath: '/app/patients/$id/edit'
      preLoaderRoute: typeof AppPatientsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppModuleRoute: typeof AppModuleRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppPatientsIdEditRoute: typeof AppPatientsIdEditRoute
  AppPatientsIdIndexRoute: typeof AppPatientsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModuleRoute: AppModuleRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReportsRoute: AppReportsRoute,
  AppSearchRoute: AppSearchRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppPatientsIdEditRoute: AppPatientsIdEditRoute,
  AppPatientsIdIndexRoute: AppPatientsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AppointmentsRoute: AppointmentsRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PortalRoute: PortalRoute,
  TendersRoute: TendersRoute,
  TestimonialsRoute: TestimonialsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevIntegrationStatusRoute: DevIntegrationStatusRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  ShopIdRoute: ShopIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
